name: Clone

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      uses: ./.github/workflows/parse

    - name: Print env vars
      shell: bash
      run: |
        echo "Tag: $FORGEJO_TAG"

    - name: Checkout Repo
      shell: bash
      run: |
        while ! git clone https://git.eden-emu.dev/eden-emu/eden.git eden; do
          echo "Clone failed!"
          sleep 5
          echo "Trying clone again..."
          rm -rf ./eden || true
        done

        cd eden
        git reset --hard d7574b2878
        git submodule update --init --recursive
